[tool.poetry]
name = "dnsforge"
version = "0.1.0"
description = ""
authors = ["Apurva Goenka <apurva.goenka2@aon.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
scapy = "^2.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
